### ISSUE TITLE
BoofCV with Java9+ (modules)

### ISSUE THREAD

**Issue by lanthale** [lessthanoptimal/BoofCV#212] opened 2021-02-14 09:49 UTC
I am developing the opensource photomanagement app https://github.com/lanthale/photoslide and wanted to use boofcv with my app. The issue is that actualy boofcv is using split packages and therefore it is not possible to use the lib with a modular application. 

There are two possible solution from my perspective:
1. Provide a fatjar which include everything, than I can add this ueber jar as a module and patch it with a module-info.class (Actually I did this manually but it is not a good way to use manual libs with maven)
2. Rename the packages so that they exists only one time over all jars. This is not possible with the java module system. (Error: Module boofcv.geo contains package boofcv.alg.geo, module boofcv.ip.multiview exports package boofcv.alg.geo to boofcv.geo)

I would appreciate if you can change the lib (package rename) so that it can be used in modular java applications.

Cheers,
Clemens

**Comment by lessthanoptimal** [comment] 2021-02-14 13:49
Duplicate of https://github.com/lessthanoptimal/BoofCV/issues/171

Maybe providing a fat jar on Maven central as a compromise?

**Comment by lessthanoptimal** [comment] 2021-02-14 16:27
Let's move the discussion over there.

**Closed as completed by lessthanoptimal** 2021-02-14 16:27 UTC
Labels: Duplicate

**Comment by lessthanoptimal** [comment] 2021-02-14 16:29
@lanthale unrelated to this ticket, the current SNAPSHOT is adding image recognition. When it's done you should be able to recognize if multiple photos are of the same scene.

**Comment by lanthale** [comment] 2021-02-14 18:21
@lessthanoptimal Great - This is realy cool. Than I would add it to the import module I am working on beside the face recognition.
I am just at the beginning of investigation how I can use boofcv beside the face recognition.
