### ISSUE TITLE
Contribution : a new image edge detection technique

### ISSUE THREAD

**Issue by SujoyKG** [lessthanoptimal/BoofCV#164] opened 2020-04-25 07:47 UTC
Hello Sir/ Madam,

I want to contribute to BoofCV with a new image edge
detection technique
[a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf](https://github.com/lessthanoptimal/BoofCV/files/4532574/a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf)
 which is more generic & better than the similar popular
techniques for the same.
The paper that I have published is attached here with this email.
Please go through it.
If you like it, please tell me the process to move next.

Thanks & Regards,
Sujoy  K Goswami
Principal Data Scientist
TVS Motor Company
India

**Comment by lessthanoptimal** [comment] 2020-04-25 18:11
Hi Sujoy,

Thanks for the contribution offer! In general the process starts by forking BoofCV, adding the code you wish to contribute to your fork, and then creating a pull request. The first pull request doesn't need to be (and probably shouldn't be) optimized production code, just something quick and dirty to show what it can do. For this type of contribution there also needs to be a demonstration that it provides improved performance against existing methods. That can either be speed or stability, based on the paper it's claiming improved stability. Also all code contributions will be under the project's license, which is Apache 2.0 and copyright assigned to this project.

I'm trying to think of a good way to compare this edge detector against the other edge detectors. The ValidationBoof project contains regression tests for BoofCV that also double as performance studies. There aren't any directly for edge detectors, but there are some minimalist ones for line detectors which use edge detectors as an input. Maybe that would be a good place to start?

**Comment by SujoyKG** [comment] 2020-04-26 02:42
Dear Owner,

Thank you for your fast response.
My gradient-operator (edge-operator) is similar to SOBEL/ PREWITT, but better than them. 
Check the link here please:
[sobel](http://boofcv.org/javadoc/boofcv/alg/filter/derivative/GradientSobel.html)

However, I am not comfortable in Java. I have the optimized code written in Python. So please help & tell how to move next.

Thanks & Regards,

**Comment by ahmadmughees** [comment] 2020-04-29 20:51
Dear @SujoyKG 
I hope you are doing well. You have built the entire code for stitching or just edge section in python?

Thanks.

**Comment by SujoyKG** [comment] 2020-04-30 03:23
Hello Sir,

Stitching means? 
I have implemented what's there in my paper. That means a new edge-operator OR gradient-operator. I have the optimized source code for that in Python. As I am not an expert in Java, so here I need help while contributing.

Thanks.

**Comment by lessthanoptimal** [comment] 2020-05-21 15:05
Could you post a link to the code? Maybe someone will be willing to port it.

P.S. this is more of a feature request than a donation since the code doesn't exist yet.

**Comment by SujoyKG** [comment] 2020-06-21 12:41
> Could you post a link to the code? Maybe someone will be willing to port it.
> 
> P.S. this is more of a feature request than a donation since the code doesn't exist yet.

[Here](https://github.com/SujoyKG/Sujoy_Edge/blob/master/edge.py) is the Python code. I can guide if someone needs help to implement/ port. Thanks.

**Comment by jeremydouglass** [comment] 2020-06-22 01:51
@SujoyKG, I'm not familiar with mahotas, but am I right that your paper / code example is based on convolving with a specific convolution kernel? If so then I think (untested) that you might be able to use the kernel from your paper directly with BoofCV ConvolveImage.

https://github.com/lessthanoptimal/BoofCV/blob/SNAPSHOT/main/boofcv-ip/src/main/java/boofcv/alg/filter/convolve/ConvolveImage.java

**Comment by SujoyKG** [comment] 2020-06-22 05:35
Can anyone please send me the link where exactly my code is to be written/ added? Also I want the link where 'Sobel operator/ filter' has got implemented in your library. Then I can try myself. Thanks.

**Comment by amarbit** [comment] 2020-11-02 05:32
Dear All,
I shall implement Sujoy Filter in BoofCV and submit. I know Java. Please help how and where to submit.

**Comment by lessthanoptimal** [comment] 2020-11-06 15:40
@amarbit maybe a good place to start looking is at the CannyEdge detector?

https://github.com/lessthanoptimal/BoofCV/tree/SNAPSHOT/main/boofcv-feature/src/main/java/boofcv/alg/feature/detect/edge

**Comment by lessthanoptimal** [comment] 2020-11-06 15:42
As for how to submit, create a PR on github and it needs to include unit tests. Continuous Integration (CI) needs to pass too. I can help with issues there to explain why it's not working and also help clean up code formatting since that's currently not strictly enforced by CI.

**Comment by lessthanoptimal** [comment] 2022-02-18 02:36
Clean up old issues. Feel free to open again if this becomes active.

**Closed as completed by lessthanoptimal** 2022-02-18 02:36 UTC
Labels: Contribution
