### ISSUE TITLE
Performance problem in PointTracker

### ISSUE THREAD

**Issue by thhart** [lessthanoptimal/BoofCV#106] opened 2018-11-30 21:42 UTC
The following code snippet shows a problem with the tracker factory. If a tracker is not reset after a couple of seconds it becomes slower and slower. I tested this with a KLT and FAST_BRIEF in version 0.30 and 0.32. In my project I use a tracker continuously on a video stream. However after some time I have to reset the processing (commented out in the code).

If you run the code for some minutes the processing steadily increases.

```

import boofcv.BoofVersion;
import boofcv.abst.feature.detect.interest.ConfigGeneralDetector;
import boofcv.abst.feature.tracker.PointTracker;
import boofcv.factory.feature.tracker.FactoryPointTracker;
import boofcv.io.image.ConvertBufferedImage;
import boofcv.struct.image.GrayU8;
import com.github.sarxos.webcam.Webcam;

public class ExampleTest {
	public static void main(String[] argv) {
		try {
			System.err.println("Testing: " + BoofVersion.VERSION);
			final ConfigGeneralDetector configDetector = new ConfigGeneralDetector(512, 6, 64);
			final PointTracker<GrayU8> tracker = FactoryPointTracker.dda_FAST_BRIEF(null, configDetector, 200, GrayU8.class);
			final Webcam webcam = Webcam.getDefault();
			long timer;
			//long timerReset = System.currentTimeMillis();
			webcam.open();
			while (true) {
				timer = System.currentTimeMillis();
				tracker.process(ConvertBufferedImage.convertFrom(webcam.getImage(), (GrayU8) null));
				tracker.spawnTracks();
				System.err.println(System.currentTimeMillis() - timer);
				//if(System.currentTimeMillis() - timerReset > 10000) {
				//   tracker.reset();
				//   timerReset = System.currentTimeMillis();
				//}
			}
		} catch (Throwable e) {
			e.printStackTrace();
		}
		System.exit(0);
	}
}
```

**Comment by lessthanoptimal** [comment] 2018-12-10 00:49
is this true for example videos provided with boofcv if you loop them? If not can you provide data that this can be replicated with. Unless you think literally any video does this.

**Comment by thhart** [comment] 2018-12-10 13:03
I am pretty sure it is for all videos. I am not aware of a video long enough from demonstration set provided, which one is longer than a couple of seconds? I think the effect is noticeable after a some time only.

**Comment by lessthanoptimal** [comment] 2019-01-11 03:17
Not able to reproduce using the ExamplePointFeatureTracker. KLT is about 2ms and SURF 16 ms. Ran for about 10 minutes. I'm running Ubuntu 18.04. What OS are you running?

**Comment by thhart** [comment] 2019-01-11 09:50
This is strange, reproduced on different OS (Ubuntu and OpenSuse), but will check and come back.

**Comment by thhart** [comment] 2019-01-11 10:20
From my point of view the tracks kept in the tracker are the problem. These will not be released after some time. I have updated the test code a bit giving following output, the last number is the size of the trackers.

```
Version: 0.32-SNAPSHOT
Name: Linux
Operating Version: 4.15.0-43-generic
Architecture: amd64
Java: Oracle Corporation, Java HotSpot(TM) 64-Bit Server VM, 25.181-b13

Fri Jan 11 11:14:33 CET 2019: 45 ms, 343
Fri Jan 11 11:14:38 CET 2019: 33 ms, 580
Fri Jan 11 11:14:43 CET 2019: 34 ms, 913
Fri Jan 11 11:14:48 CET 2019: 31 ms, 1091
Fri Jan 11 11:14:54 CET 2019: 34 ms, 1333
Fri Jan 11 11:14:59 CET 2019: 46 ms, 1621
Fri Jan 11 11:15:04 CET 2019: 34 ms, 2030
Fri Jan 11 11:15:09 CET 2019: 34 ms, 2301
Fri Jan 11 11:15:14 CET 2019: 58 ms, 2561
Fri Jan 11 11:15:19 CET 2019: 69 ms, 2883
Fri Jan 11 11:15:24 CET 2019: 61 ms, 3243
Fri Jan 11 11:15:29 CET 2019: 54 ms, 3468
Fri Jan 11 11:15:34 CET 2019: 65 ms, 3644
Fri Jan 11 11:15:39 CET 2019: 69 ms, 4010
Fri Jan 11 11:15:44 CET 2019: 70 ms, 4187
Fri Jan 11 11:15:49 CET 2019: 69 ms, 4343
Fri Jan 11 11:15:54 CET 2019: 64 ms, 4617
Fri Jan 11 11:15:59 CET 2019: 56 ms, 4771
Fri Jan 11 11:16:04 CET 2019: 67 ms, 4935
Fri Jan 11 11:16:09 CET 2019: 70 ms, 5117
Fri Jan 11 11:16:14 CET 2019: 67 ms, 5315
Fri Jan 11 11:16:19 CET 2019: 65 ms, 5492
Fri Jan 11 11:16:24 CET 2019: 74 ms, 5681
Fri Jan 11 11:16:29 CET 2019: 80 ms, 5885
Fri Jan 11 11:16:34 CET 2019: 67 ms, 6086

```

This is the testing code:

```
package boofcv.examples;

import boofcv.BoofVersion;
import boofcv.abst.feature.detect.interest.ConfigGeneralDetector;
import boofcv.abst.feature.tracker.PointTracker;
import boofcv.factory.feature.tracker.FactoryPointTracker;
import boofcv.io.image.ConvertBufferedImage;
import boofcv.struct.image.GrayU8;
import com.github.sarxos.webcam.Webcam;

import java.util.Date;

public class ExampleTest {
	public static void main(String[] argv) {
		try {
			System.out.println("Version: " + BoofVersion.VERSION);
			System.out.println("Name: " + System.getProperty("os.name"));
			System.out.println("Operating Version: " + System.getProperty("os.version"));
			System.out.println("Architecture: " + System.getProperty("os.arch"));
			System.out.println("Java: " + System.getProperty("java.vm.vendor") + ", " + System.getProperty("java.vm.name") + ", " + System.getProperty("java.vm.version"));
			final ConfigGeneralDetector configDetector = new ConfigGeneralDetector(512, 6, 64);
			final PointTracker<GrayU8> tracker = FactoryPointTracker.dda_FAST_BRIEF(null, configDetector, 200, GrayU8.class);
			final Webcam webcam = Webcam.getDefault();
			long timer;
			long timerReport = System.currentTimeMillis();
			long timerReset = System.currentTimeMillis();
			webcam.open();
			while (true) {
				timer = System.currentTimeMillis();
				tracker.process(ConvertBufferedImage.convertFrom(webcam.getImage(), (GrayU8) null));
				tracker.spawnTracks();
				if(System.currentTimeMillis() - timerReport > 5000) {
					System.out.println((new Date()) + ": " + (System.currentTimeMillis() - timer) + " ms, " + tracker.getAllTracks(null).size());
					timerReport = System.currentTimeMillis();
				}
//				if(System.currentTimeMillis() - timerReset > 10000) {
//					tracker.reset();
//					timerReset = System.currentTimeMillis();
//				}
			}
		} catch (Throwable e) {
			e.printStackTrace();
		}
		System.exit(0);
	}
}

```

**Comment by lessthanoptimal** [comment] 2019-01-13 16:58
I've been able to reproduce. The example code only occasionally spawns new tracks or never if it doesn't drop enough features. Just updated VideoTrackerPointFeaturesApp to use the more modern application interface. You can now open videos and webcams and tune some settings live.

**Comment by lessthanoptimal** [comment] 2019-02-27 03:10
I pushed a fix. You can limit the number of unassociated tracks it maintains.  Still going to do testing to make sure this doesn't mess up any other algorithms which use this tracker.

**Comment by lessthanoptimal** [comment] 2019-03-24 14:36
No complains and new stable was released. i'm assuming this is fixed.

**Closed by lessthanoptimal** 2019-03-24 14:36 UTC
Labels: Testing Fix, verified
