### ISSUE TITLE
Lombok dependencies

### ISSUE THREAD

**Issue by wkornewald** [lessthanoptimal/BoofCV#319] opened 2021-12-13 08:06 UTC
We received a complaint that Lombok-related files are in our CovPass APK: https://github.com/Digitaler-Impfnachweis/covpass-android/issues/133

Could you please check if the dependencies can be optimized/reduced a little bit in boofcv-core? Otherwise we can also try to strip unnecessary files and deps on our end, but I thought it might be nicer for all users if the issue could be solved in BoofCV.

**Comment by lessthanoptimal** [comment] 2021-12-13 12:51
That's probably a miss configuration because Lombok should be compile time only. I'll look into this early this week. Traveling right now.

**Comment by wkornewald** [comment] 2021-12-13 13:11
It’s nothing time critical anyway. Thank you and enjoy your trip!

**Comment by G00fY2** [comment] 2021-12-13 18:57
Looks like the `boofcv-types` module has a runtime dependency on lombok. Below is the relevant part of the `gradlew app-covpass-prod:dependencies --configuration releaseRuntimeClasspath` output.

Maybe there are more dependencies that are not required at runtime? Lombok was just easy to find, because it causes multiple folders and files to show up in the APK.

```
|    |    +--- org.boofcv:boofcv-core:0.39.1
|    |    |    +--- org.georegression:georegression:0.24
|    |    |    |    \--- org.ddogleg:ddogleg:0.20
|    |    |    |         +--- org.ejml:ejml-core:0.41
|    |    |    |         +--- org.ejml:ejml-fdense:0.41
|    |    |    |         |    \--- org.ejml:ejml-core:0.41
|    |    |    |         +--- org.ejml:ejml-ddense:0.41
|    |    |    |         |    \--- org.ejml:ejml-core:0.41
|    |    |    |         +--- org.ejml:ejml-simple:0.41
|    |    |    |         |    +--- org.ejml:ejml-core:0.41
|    |    |    |         |    +--- org.ejml:ejml-fdense:0.41 (*)
|    |    |    |         |    +--- org.ejml:ejml-ddense:0.41 (*)
|    |    |    |         |    +--- org.ejml:ejml-cdense:0.41
|    |    |    |         |    |    \--- org.ejml:ejml-core:0.41
|    |    |    |         |    +--- org.ejml:ejml-zdense:0.41
|    |    |    |         |    |    \--- org.ejml:ejml-core:0.41
|    |    |    |         |    +--- org.ejml:ejml-dsparse:0.41
|    |    |    |         |    |    +--- org.ejml:ejml-core:0.41
|    |    |    |         |    |    \--- org.ejml:ejml-ddense:0.41 (*)
|    |    |    |         |    \--- org.ejml:ejml-fsparse:0.41
|    |    |    |         |         +--- org.ejml:ejml-core:0.41
|    |    |    |         |         \--- org.ejml:ejml-fdense:0.41 (*)
|    |    |    |         \--- org.ejml:ejml-dsparse:0.41 (*)
|    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    +--- org.boofcv:boofcv-feature:0.39.1
|    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    +--- org.boofcv:boofcv-ip:0.39.1
|    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    \--- org.boofcv:boofcv-types:0.39.1
|    |    |    |    |         +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |         +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |         +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |         +--- org.projectlombok:lombok:1.18.20
|    |    |    |    |         +--- org.jetbrains:annotations:20.0.0 -> 20.1.0
|    |    |    |    |         \--- javax.annotation:jsr250-api:1.0
|    |    |    |    \--- org.boofcv:boofcv-geo:0.39.1
|    |    |    |         +--- org.georegression:georegression:0.24 (*)
|    |    |    |         +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |         +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |         \--- org.boofcv:boofcv-types:0.39.1 (*)
|    |    |    +--- org.boofcv:boofcv-geo:0.39.1 (*)
|    |    |    +--- org.boofcv:boofcv-io:0.39.1
|    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    +--- org.boofcv:boofcv-ip:0.39.1 (*)
|    |    |    |    +--- org.boofcv:boofcv-geo:0.39.1 (*)
|    |    |    |    +--- org.boofcv:boofcv-sfm:0.39.1
|    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    +--- org.boofcv:boofcv-ip-multiview:0.39.1
|    |    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    |    +--- org.boofcv:boofcv-geo:0.39.1 (*)
|    |    |    |    |    |    +--- org.boofcv:boofcv-ip:0.39.1 (*)
|    |    |    |    |    |    \--- org.boofcv:boofcv-feature:0.39.1 (*)
|    |    |    |    |    +--- org.boofcv:boofcv-feature:0.39.1 (*)
|    |    |    |    |    \--- org.boofcv:boofcv-geo:0.39.1 (*)
|    |    |    |    +--- org.boofcv:boofcv-recognition:0.39.1
|    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    +--- org.boofcv:boofcv-ip:0.39.1 (*)
|    |    |    |    |    +--- org.boofcv:boofcv-feature:0.39.1 (*)
|    |    |    |    |    +--- org.boofcv:boofcv-geo:0.39.1 (*)
|    |    |    |    |    +--- org.deepboof:main:0.5.1
|    |    |    |    |    +--- org.deepboof:models:0.5.1
|    |    |    |    |    |    +--- org.deepboof:main:0.5.1
|    |    |    |    |    |    +--- org.deepboof:learning:0.5.1
|    |    |    |    |    |    |    \--- org.deepboof:main:0.5.1
|    |    |    |    |    |    \--- org.deepboof:io:0.5.1
|    |    |    |    |    |         +--- com.google.protobuf:protobuf-java:3.17.3
|    |    |    |    |    |         +--- org.deepboof:main:0.5.1
|    |    |    |    |    |         +--- org.rauschig:jarchivelib:1.1.0
|    |    |    |    |    |         \--- net.lingala.zip4j:zip4j:2.8.0
|    |    |    |    |    \--- org.deepboof:io:0.5.1 (*)
|    |    |    |    +--- org.boofcv:boofcv-reconstruction:0.39.1
|    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    +--- org.boofcv:boofcv-recognition:0.39.1 (*)
|    |    |    |    |    \--- org.boofcv:boofcv-sfm:0.39.1 (*)
|    |    |    |    +--- org.yaml:snakeyaml:1.23
|    |    |    |    \--- commons-io:commons-io:2.11.0
|    |    |    +--- org.boofcv:boofcv-ip:0.39.1 (*)
|    |    |    +--- org.boofcv:boofcv-ip-multiview:0.39.1 (*)
|    |    |    +--- org.boofcv:boofcv-learning:0.39.1
|    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    +--- org.boofcv:boofcv-ip:0.39.1 (*)
|    |    |    |    +--- org.boofcv:boofcv-feature:0.39.1 (*)
|    |    |    |    +--- org.boofcv:boofcv-recognition:0.39.1 (*)
|    |    |    |    +--- org.boofcv:boofcv-geo:0.39.1 (*)
|    |    |    |    \--- org.boofcv:boofcv-sfm:0.39.1 (*)
|    |    |    +--- org.boofcv:boofcv-recognition:0.39.1 (*)
|    |    |    +--- org.boofcv:boofcv-reconstruction:0.39.1 (*)
|    |    |    +--- org.boofcv:boofcv-sfm:0.39.1 (*)
|    |    |    \--- org.boofcv:boofcv-types:0.39.1 (*)
|    |    +--- org.boofcv:boofcv-android:0.39.1
|    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    +--- org.boofcv:boofcv-ip:0.39.1 (*)
|    |    |    +--- org.boofcv:boofcv-feature:0.39.1 (*)
|    |    |    \--- org.boofcv:boofcv-geo:0.39.1 (*)
```

**Comment by lessthanoptimal** [comment] 2021-12-20 01:01
https://github.com/lessthanoptimal/BoofCV/pull/320 fixed it. Will be in SNAPSHOT momentarily

**Comment by lessthanoptimal** [comment] 2021-12-20 01:03
@G00fY2 Yep you found the leak. A gradle dependency was marked as "implementation" instead of "compileOnly" and that caused the accidental transitive dependency. This is related to some hackery to avoid a cyclical dependency as a result of auto code generation.

**Comment by lessthanoptimal** [comment] 2021-12-20 01:11
I'm fairly confident this is fixed since I don't see the dependency any more. Feel free to re-open if this is not the case.

**Closed as completed by lessthanoptimal** 2021-12-20 01:11 UTC
Labels: Fixed

**Comment by wkornewald** [comment] 2021-12-20 12:43
Thanks a lot!

**Comment by G00fY2** [comment] 2021-12-20 13:25
I just cloned the SNAPSHOT branch, build the latest _0.40-SNAPSHOT_ locally and switched the version inside the covpass app. I can confirm that the lombok runtime dependency is fixed. :slightly_smiling_face:

```
|    |    +--- org.boofcv:boofcv-core:0.40-SNAPSHOT
|    |    |    +--- org.georegression:georegression:0.24
|    |    |    |    \--- org.ddogleg:ddogleg:0.20
|    |    |    |         +--- org.ejml:ejml-core:0.41
|    |    |    |         +--- org.ejml:ejml-fdense:0.41
|    |    |    |         |    \--- org.ejml:ejml-core:0.41
|    |    |    |         +--- org.ejml:ejml-ddense:0.41
|    |    |    |         |    \--- org.ejml:ejml-core:0.41
|    |    |    |         +--- org.ejml:ejml-simple:0.41
|    |    |    |         |    +--- org.ejml:ejml-core:0.41
|    |    |    |         |    +--- org.ejml:ejml-fdense:0.41 (*)
|    |    |    |         |    +--- org.ejml:ejml-ddense:0.41 (*)
|    |    |    |         |    +--- org.ejml:ejml-cdense:0.41
|    |    |    |         |    |    \--- org.ejml:ejml-core:0.41
|    |    |    |         |    +--- org.ejml:ejml-zdense:0.41
|    |    |    |         |    |    \--- org.ejml:ejml-core:0.41
|    |    |    |         |    +--- org.ejml:ejml-dsparse:0.41
|    |    |    |         |    |    +--- org.ejml:ejml-core:0.41
|    |    |    |         |    |    \--- org.ejml:ejml-ddense:0.41 (*)
|    |    |    |         |    \--- org.ejml:ejml-fsparse:0.41
|    |    |    |         |         +--- org.ejml:ejml-core:0.41
|    |    |    |         |         \--- org.ejml:ejml-fdense:0.41 (*)
|    |    |    |         \--- org.ejml:ejml-dsparse:0.41 (*)
|    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    +--- org.boofcv:boofcv-feature:0.40-SNAPSHOT
|    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    +--- org.boofcv:boofcv-ip:0.40-SNAPSHOT
|    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    \--- org.boofcv:boofcv-types:0.40-SNAPSHOT
|    |    |    |    |         +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |         +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |         \--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    \--- org.boofcv:boofcv-geo:0.40-SNAPSHOT
|    |    |    |         +--- org.georegression:georegression:0.24 (*)
|    |    |    |         +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |         +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |         \--- org.boofcv:boofcv-types:0.40-SNAPSHOT (*)
|    |    |    +--- org.boofcv:boofcv-geo:0.40-SNAPSHOT (*)
|    |    |    +--- org.boofcv:boofcv-io:0.40-SNAPSHOT
|    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    +--- org.boofcv:boofcv-ip:0.40-SNAPSHOT (*)
|    |    |    |    +--- org.boofcv:boofcv-geo:0.40-SNAPSHOT (*)
|    |    |    |    +--- org.boofcv:boofcv-sfm:0.40-SNAPSHOT
|    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    +--- org.boofcv:boofcv-ip-multiview:0.40-SNAPSHOT
|    |    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    |    +--- org.boofcv:boofcv-geo:0.40-SNAPSHOT (*)
|    |    |    |    |    |    +--- org.boofcv:boofcv-ip:0.40-SNAPSHOT (*)
|    |    |    |    |    |    \--- org.boofcv:boofcv-feature:0.40-SNAPSHOT (*)
|    |    |    |    |    +--- org.boofcv:boofcv-feature:0.40-SNAPSHOT (*)
|    |    |    |    |    \--- org.boofcv:boofcv-geo:0.40-SNAPSHOT (*)
|    |    |    |    +--- org.boofcv:boofcv-recognition:0.40-SNAPSHOT
|    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    +--- org.boofcv:boofcv-ip:0.40-SNAPSHOT (*)
|    |    |    |    |    +--- org.boofcv:boofcv-feature:0.40-SNAPSHOT (*)
|    |    |    |    |    +--- org.boofcv:boofcv-geo:0.40-SNAPSHOT (*)
|    |    |    |    |    +--- org.deepboof:main:0.5.1
|    |    |    |    |    +--- org.deepboof:models:0.5.1
|    |    |    |    |    |    +--- org.deepboof:main:0.5.1
|    |    |    |    |    |    +--- org.deepboof:learning:0.5.1
|    |    |    |    |    |    |    \--- org.deepboof:main:0.5.1
|    |    |    |    |    |    \--- org.deepboof:io:0.5.1
|    |    |    |    |    |         +--- com.google.protobuf:protobuf-java:3.17.3
|    |    |    |    |    |         +--- org.deepboof:main:0.5.1
|    |    |    |    |    |         +--- org.rauschig:jarchivelib:1.1.0
|    |    |    |    |    |         \--- net.lingala.zip4j:zip4j:2.8.0
|    |    |    |    |    \--- org.deepboof:io:0.5.1 (*)
|    |    |    |    +--- org.boofcv:boofcv-reconstruction:0.40-SNAPSHOT
|    |    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    |    +--- org.boofcv:boofcv-recognition:0.40-SNAPSHOT (*)
|    |    |    |    |    \--- org.boofcv:boofcv-sfm:0.40-SNAPSHOT (*)
|    |    |    |    +--- org.yaml:snakeyaml:1.23
|    |    |    |    \--- commons-io:commons-io:2.11.0
|    |    |    +--- org.boofcv:boofcv-ip:0.40-SNAPSHOT (*)
|    |    |    +--- org.boofcv:boofcv-ip-multiview:0.40-SNAPSHOT (*)
|    |    |    +--- org.boofcv:boofcv-learning:0.40-SNAPSHOT
|    |    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    |    +--- org.boofcv:boofcv-ip:0.40-SNAPSHOT (*)
|    |    |    |    +--- org.boofcv:boofcv-feature:0.40-SNAPSHOT (*)
|    |    |    |    +--- org.boofcv:boofcv-recognition:0.40-SNAPSHOT (*)
|    |    |    |    +--- org.boofcv:boofcv-geo:0.40-SNAPSHOT (*)
|    |    |    |    \--- org.boofcv:boofcv-sfm:0.40-SNAPSHOT (*)
|    |    |    +--- org.boofcv:boofcv-recognition:0.40-SNAPSHOT (*)
|    |    |    +--- org.boofcv:boofcv-reconstruction:0.40-SNAPSHOT (*)
|    |    |    +--- org.boofcv:boofcv-sfm:0.40-SNAPSHOT (*)
|    |    |    \--- org.boofcv:boofcv-types:0.40-SNAPSHOT (*)
|    |    +--- org.boofcv:boofcv-android:0.40-SNAPSHOT
|    |    |    +--- org.georegression:georegression:0.24 (*)
|    |    |    +--- org.ddogleg:ddogleg:0.20 (*)
|    |    |    +--- net.sf.trove4j:trove4j:3.0.3
|    |    |    +--- org.boofcv:boofcv-ip:0.40-SNAPSHOT (*)
|    |    |    +--- org.boofcv:boofcv-feature:0.40-SNAPSHOT (*)
|    |    |    \--- org.boofcv:boofcv-geo:0.40-SNAPSHOT (*)
```
